---    
- name: Create directory layout
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
  with_items: "{{ web_directories }}"
  become: true
  remote_user: "{{ sudo_user }}"
  when: item | length > 0
   
  
- include_tasks: 
    file: vhost.yml
    
- include_tasks: assets.yml
  loop_control:
    loop_var: tenant
  loop: "{{ tenants }}"    